port: 3000
channels:
  - id: lrt
    url: https://www.lrt.lt/servisai/stream_url/live/get_live_url.php?channel=LTV1
    streamUrlPath: response.data.content
    contentType: application/vnd.apple.mpegurl
    programUrl: https://www.lrt.lt/programa
    programSelector: 'div[data-slider-id="$date$"]'
    programStylesheet: https://www.lrt.lt/css/app.css
    programScrollTo: .is-playing
  - id: lrtplus
    url: https://www.lrt.lt/servisai/stream_url/live/get_live_url.php?channel=LTV2
    streamUrlPath: response.data.content
    contentType: application/vnd.apple.mpegurl
    programUrl: https://www.lrt.lt/programa
    programSelector: 'div[data-slider-id="$date$"]'
    programStylesheet: https://www.lrt.lt/css/app.css
    programScrollTo: .is-playing
  - id: lnk
    url: https://lnk.lt/api/video/video-config/137535
    streamUrlPath: videoInfo.videoUrl
    contentType: application/vnd.apple.mpegurl
    programUrl: https://lnk.lt/api/main/schedule/2/%s
    programScrollTo: .is-playing
    programLocalStylesheet: lnk.css
  - id: btv
    url: https://lnk.lt/api/video/video-config/137534
    streamUrlPath: videoInfo.videoUrl
    contentType: application/vnd.apple.mpegurl
    programUrl: https://lnk.lt/api/main/schedule/3/%s
    programScrollTo: .is-playing
    programLocalStylesheet: lnk.css
  - id: 2tv
    url: https://lnk.lt/api/video/video-config/95343
    streamUrlPath: videoInfo.videoUrl
    contentType: application/vnd.apple.mpegurl
    programUrl: https://lnk.lt/api/main/schedule/6/%s
    programScrollTo: .is-playing
    programLocalStylesheet: lnk.css
  - id: infotv 
    url: https://lnk.lt/api/video/video-config/137748
    streamUrlPath: videoInfo.videoUrl
    contentType: application/vnd.apple.mpegurl
    programUrl: https://lnk.lt/api/main/schedule/5/%s
    programScrollTo: .is-playing
    programLocalStylesheet: lnk.css
  - id: tv1
    url: https://lnk.lt/api/video/video-config/106791
    streamUrlPath: videoInfo.videoUrl
    contentType: application/vnd.apple.mpegurl
    programUrl: https://lnk.lt/api/main/schedule/4/%s
    programScrollTo: .is-playing
    programLocalStylesheet: lnk.css
